print ("Nama = Regina Arum Saraswati Rahma")
print ("Nama Panggilan = Regina")
print ("NIM = I0322104")
print ("Alamat = Jalan I Gusti Ngurah Rai, Gang Bhayangkari, No 05, RT 03, RW 01, Bago, Tulungagung")
print ("======================================")
print ("Deskripsi Tempat Tinggal = Saya tinggal di kota Tulungagung yang terkenal dengan penghasil marmer terbesar di Indonesia")
print ("Selain itu Tulungagung juga dikenal sebagai kota seribu warung kopi")
print ("Tulungagung juga mempunyai wisata pantai yang eksotik")
print ("Makanan khas dari kota Tulungagung yaitu kerupuk kulit rambak, ayam lodho,jenang syabun, dan punten pecel")
print ("======================================")
print ("Harapan sebagai lulusan Teknik Industri = Harapan saya sebagai lulusan teknik industri dapat mengembangkan perindustrian di indonesia dan bekerja di perusahaan bidang manufaktur")